name: Check for any build error

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]  # Specify a minor version
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Run npm audit
        id: npm_audit
        run: npm audit --production
      - name: Print vulnerabilities
        run: |
          echo "Vulnerabilities found:"
          echo "${{ steps.npm_audit.outputs.audit }}"
      - run: npm run build --if-present
      - name: Run Tests
        run: npm test
      - name: Print Node.js version
        run: node -v  # Add this to confirm the Node.js version
      - name: Print npm version
        run: npm -v  # Add this to confirm the npm version
